version: "3"
services:
  db-service:
    image: ngodanghai9x/mysql-learn-nestjs:8.0.32
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    networks:
      - my-net

  cache-service:
    image: redis:7.0.9-alpine
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data

  be-service:
    build: .
    ports:
      - "3005:3005"
    environment:
      MYSQL_HOST: db-service
      REDIS_HOST: cache-service
    volumes:
      # - .:/app
      - ./:/app
    networks:
      - my-net
    depends_on:
      - db-service
      - cache-service
      
volumes:
  db-data:
  cache-data:

networks: 
  my-net:
    driver: bridge
